//Package trakt ...
package trakt

const (
	//TraktAPIURL      = "https://api-v2launch.trakt.tv"
	//TraktAPIURL      = "https://api.trakt.tv"
	//TraktAPIURL ...
	TraktAPIURL      = "https://private-anon-6ff2bfe4be-trakt.apiary-mock.com"
	
	//TraktAPIVersion ...
	TraktAPIVersion  = "2"
	//UserAgent ...
	UserAgent        = "Trakt Go " + Version
	//Version ...
	Version          = "0.0.1"
	//DefaultMediaType ...
	DefaultMediaType = "application/json"
)
